### ISSUE TITLE
Question: Loop for alignment 

### ISSUE THREAD

**Issue by FernandaDiaz12** [FernandaDiaz12/pediatric_astrocytoma#2]
# Hi, everyone!

I am struggling with the code to create a loop to align my paired-end reads to a reference genome (Human Genome hg38). 

### As a quick introduction: 
I decided to use STAR to align my 2x125 reads because it's a tool that enables highly accurate and ultra-fast alignment of RNA-seq reads to a reference genome. 

The code line to align with STAR is: 

`STAR --runThreadN X --runMode alignReads --genomeDir STAR/star_indices/ --readFilesIn nnnnn_R1_001.fastq nnnnn_R2_001.fastq --outFileNamePrefix outFILE.sam`

Where:

- *runThreadN*  .- number of processors 
- *runMode* .- Align or index
- *genomeDir*.-  Directory w/ indexed reference genome
- *readFilesIn*.- fastq files
- *outFileNamePrefix*.- Name of the outputfile 

So.... I want to create a loop that aligns each pair of reads and create a single sam file. 

In other words: I want a loop that makes this: 

`STAR --runThreadN 18 --runMode alignReads --genomeDir STAR/star_indices/ --readFilesIn raw_data/A10A_S16_L004_R1_001.fastq raw_data/A10A_S16_L004_R2_001.fastq --outFileNamePrefix SAM_START_files/A10A_`

You can find the code in this [script](https://github.com/FernandaDiaz12/pediatric_astrocytoma/blob/master/bin/3.%20STAR.sh)

For my 21 samples (42 fastq files)

### The problem is 
I need that both reads (R1 and R2) with the same name are aligned in each turn of the loop. And that the output file keeps the reads sample name. 

To solve this problem I made a file with only 10,000 reads for eight fastq files (Four pair-end). That you can find [here](https://github.com/FernandaDiaz12/pediatric_astrocytoma/tree/master/data/Small_Fastq). Also, we will need the indexed genome is in [here](https://github.com/FernandaDiaz12/pediatric_astrocytoma/tree/master/data/star_indices). 

What I've tried to solve the problem is: 

```
##Loop to align
#Prefix=variable
for prefix in $(ls *.fastq | rev | cut -c 14- | rev | uniq);
do;
STAR  --readFilesIn ${prefix}_R1_002.fastq ${prefix}_R2_002.fastq  \
--runThreadN 18 --runMode alignReads --genomeDir star_indices/  \
 --outFileNamePrefix ${prefix%.fastq}_
 done

```

Where the list of variables is defined by: 
`$(ls *.fastq | rev | cut -c 13- | rev | uniq)`
 
1. Pick all .fastq files (ls to display the names of *fastq)
2. Reverse their names (To start counting the characters from the end)
3. Pick from char 13 to end ( Cut off the last 13 characters -->_**R12**_002.fastq)
4. Reverse again (as the last 13 characters are constant, we use that to pick first n characters)
5. Take a uniq on this prefix set.

As you can see I need that the item prefix = Name of the sample (regarding if it´s R1 or R2).

The Error that appears seems to be that the file can't be opened: 

> EXITING because of fatal input ERROR: could not open readFilesIn=A10A_S16_L004__R1_002.fastq

>EXITING because of fatal input ERROR: could not open readFilesIn=A12A_S17_L004__R1_002.fastq

>EXITING because of fatal input ERROR: could not open readFilesIn=A12B_S18_L004__R1_002.fastq

>EXITING because of fatal input ERROR: could not open readFilesIn=CM8_S13_L004__R1_002.fastq

But part of the loop runs because the files that are created when STAR runs appear in the output directory. 

So I think the problem has to do with how am I giving the command tho choose the files. 

### HELP :(

Thank you!

**Comment by AliciaMstt** [comment]
It seems the file can't be opened likely because the file name is not correct, that is, your variables inside the loop no are what you think they are. A tip to check this is running your commands of the loop **inside an `eco`** this prints the command as the computer will run it, and allows you to check if there is an error. 

For instance try:

```
for prefix in $(ls Small_fastq/*.fastq | rev | cut -c 13- | rev | uniq); do
echo "STAR  --readFilesIn ${prefix}_R1_002.fastq ${prefix}_R2_002.fastq  --runThreadN 18 --runMode alignReads --genomeDir star_indices/ --outFileNamePrefix ${prefix%.fastq}_"
done 
```

by the way: there was an error in your example it should be: `ls Small_fastq/*.fastq` instead of `Small_fastq/ls*.fastq` in your prefix variable construction.

**Comment by Duhyadi** [comment]
It would be necessary to point out the other variable of the second prefix ($). Specifically in the second line.That is to say. Before: `  "STAR  --readFilesIn ${prefix}_R1_002.fastq {prefix}_R2_002.fastq ` After: `"STAR  --readFilesIn ${prefix}_R1_002.fastq ${prefix}_R2_002.fastq `

**Comment by FernandaDiaz12** [comment]
#### The number of cut out characters was wrong. Instead of -c 13-. 

If I echo the example: 

`STAR  --readFilesIn A10A_S16_L004 _R_ R1_002.fastq A10A_S16_L004 **_R** _R2_002.fastq  --runThreadN 18 --runMode alignReads --genomeDir star_indices/   --outFileNamePrefix A10A_S16_L004_R_`

You can see that you have an extra **R** in the names. 
I had to put -c 14- and  the echo is:

`STAR  --readFilesIn CM8_S13_L004_R1_002.fastq CM8_S13_L004_R2_002.fastq  --runThreadN 18 --runMode alignReads --genomeDir star_indices/   --outFileNamePrefix CM8_S13_L004_`


#### Also:

In the first line, you have to take out the name of the directory.

`for prefix in $(ls .fastq | rev | cut -c 14- | rev | uniq);`

instead of:

`for prefix in $(ls Small_fastq/.fastq | rev | cut -c 13- | rev | uniq);`

### Correct syntax

```
##Loop for alignment
for prefix in $(ls *.fastq | rev | cut -c 14- | rev | uniq);
do;
STAR --readFilesIn ${prefix}_R1_002.fastq ${prefix}_R2_002.fastq; --runThreadN 18 --runMode alignReads --genomeDir star_indices/; --outFileNamePrefix ${prefix%.fastq}_; 
done 
```

#### The example in the issue was corrected with Alicia's and Duhyadi's comments.

**Comment by FernandaDiaz12** [comment]
The correct syntax is: 
##Loop for alignment
for prefix in $(ls *.fastq | rev | cut -c 14- | rev | uniq);
do;
"STAR  --readFilesIn ${prefix}_R1_002.fastq ${prefix}_R2_002.fastq;
--runThreadN 18 --runMode alignReads --genomeDir star_indices/;
 --outFileNamePrefix ${prefix%.fastq}_;
 done

**Comment by FernandaDiaz12** [comment]
As you can see, in the first line you have to take out the name of the directory. 
for prefix in $(ls *.fastq | rev | cut -c 14- | rev | uniq); 
instead of:
for prefix in $(ls Small_fastq/*.fastq | rev | cut -c 13- | rev | uniq);
